- name: set mariadb.repo
  template: src=mariadb.repo.j2 dest=/etc/yum.repos.d/mariadb.repo

- name: install mariadb
  yum: name={{item}} state=installed
  with_items:
    - MariaDB-server
    - MariaDB-client

- name: install MySQL-python
  yum: name=MySQL-python state=installed

- name: run mysql-server
  service: name=mysql state=running enabled=yes

- name: copy cnf
  template: src=server.cnf.j2  dest=/etc/my.cnf.d/server.cnf
  changed_when: False
  notify: mysqld restart

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
    - '%'

