version: 0.0
os: linux
files:
  - source: mybook/
    destination: /var/www/django/mybook

  - source: /
    destination: /tmp/mybook

hooks:
  ApplicationStop:
    - location: codedeploy/applicationStop.sh
      timeout: 180
      runas: root

  AfterInstall:
    - location: codedeploy/afterInstall.sh
      timeout: 180
      runas: ec2-user

  ApplicationStart:
    - location: codedeploy/applicationStart.sh
      timeout: 180
      runas: root

