version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/mybook

hooks:
  ApplicationStop:
    - location: codedeploy/applicationStop.sh
      timeout: 180
      runas: root

  BeforeInstall:
    - location: codedeploy/beforeInstall.sh
      timeout: 180
      runas: root

  AfterInstall:
    - location: codedeploy/afterInstall.sh
      timeout: 1800
      runas: ec2-user

  ApplicationStart:
    - location: codedeploy/applicationStart.sh
      timeout: 180
      runas: root

