- include_vars: vars.json
- name: disable SELinux
  shell: setenforce 0
  ignore_errors: true

- name: conf SELinux
  template: src=selinux-config.j2 dest=/etc/selinux/config

- include: python_install.yml

- name: install virtualenv
  pip: name=virtualenv

- name: install uwsgi
  pip: name=uwsgi virtualenv=/opt/virtualenv/uwsgi virtualenv_python={{ directories.Python3.prefix }}bin/python3

- name: install python library
  pip: requirements={{deploy_path}}/{{app_name}}/requirements.txt virtualenv=/opt/virtualenv/{{app_name}} virtualenv_python={{ directories.Python3.prefix }}bin/python3

- include: nginx_install.yml

- name: set nginx app conf
  file: src={{deploy_path}}/{{app_name}}/{{app_name}}_nginx.conf dest=/etc/nginx/conf.d/{{app_name}}_nginx.conf state=link


