- hosts: all 
  sudo: yes
  vars:
    db_username: portforest
    db_password: portforest
    db_name: portforest
    db_host: localhost
    mysql_root_password: root
    app_name: mybook
    deploy_path: "/var/www/django/"
  roles:
    - mariadb
    - initdb
    - initsrv




